### ISSUE TITLE
Boolean expression must not be null

### ISSUE THREAD

**Issue by exts** [xamantra/momentum#18]
When I have more than one config(lazy: false) controller set (and this has only happened when I have two controllers w/ custom config calls. I get this error:

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building FutureBuilder<bool>(dirty, state: _FutureBuilderState<bool>#33b89):
Failed assertion: boolean expression must not be null

The relevant error-causing widget was: 
  Momentum file:///Z:/Programming/Flutter/mywir/lib/main.dart:17:5
When the exception was thrown, this was the stack: 
#0      _MomentumRootState.build.<anonymous closure> (package:momentum/src/momentum_base.dart:1055:22)
#1      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:732:55)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
```

Going to see if I can create a reproduction of this error because I'm not doing anything crazy, I just wanted to make both controllers unlazy 

```dart
    Momentum(
      disabledPersistentState: true,
      controllers: [
        ItemIndexController()..config(lazy: false),
        ItemManageController(),
        LabelManageController(),
        LabelIndexController()..config(lazy: false),
      ],
```

If I remove config lazy on the first result no problem app loads normally. albeit my bootstrap isn't set until I call that controller.

**Comment by exts** [comment]
I'm an idiot, it's something I did lol. Couldnt figure out where the error was coming from. Turns out i forgot to set the default boolean value before passing it eg.:

```dart
  @override
  void update({
    DateTime date,
    bool loading,
    bool useDefault,
  }) {
    useDefault = useDefault ?? true; // this wasn't here before i readded it . 
    ItemIndexModel(
      this.controller,
      date: date ?? dOn(useDefault, this.date),
      items: dOn(useDefault, this.items),
      loadingData: loading ?? dOn(useDefault, this.loadingData),
    ).updateMomentum();
  }
```

I did it [here](https://github.com/exts/momentum_label_manager/blob/master/lib/domain/labels/label_model.dart#L55) which explains what I was doing lol.

Since sometimes when editing and vs creating a new item, I want it to either use the default value or set it to null because the controller keeps the model data in tact until we request it to be changed or the app restarts
